apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: preview-server
  region: us-west-2

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.large
    desiredCapacity: 2
    privateNetworking: true