apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: preview-server
  region: us-west-2

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: p2.xlarge
    desiredCapacity: 1
    privateNetworking: true
    NodeAutoScalingGroupDesiredCapacity: 2
    NodeAutoScalingGroupMaxSize: 3
    NodeAutoScalingGroupMinSize: 1